### ISSUE TITLE
WASM support, and fix make currrent build work in WASM

### ISSUE THREAD

**Issue by danilw** [lawnjelly/godot-lsimd#1]
**About WASM SIMD** support, look like it exists only in Chrome Canary, https://twitter.com/v8js/status/1222944308183085058

> V8 WebAssembly support is available in Chrome Canary and can be enabled using the --enable-features=WebAssemblySimd flag. Support is still experimental and subject to change, as this is tracking the evolution of the WebAssembly SIMD proposal.

and adding support required renaming SSE functions to `wasm_` style

**Fix to make this code work in web**:
file `simd_cpu.cpp` need to hide `Godot_CPU::xgetbv` function from wasm compiler, I have add simple:
`#ifndef JAVASCRIPT_ENABLED` on line 242, and `#endif` on line 256
it builds and works

thanks for this very useful code

**Comment by lawnjelly** [comment]
Feel free to make a PR! :grin: And I'll merge it.

I haven't tested at all on any other platforms than linux, so that will be great if it works on HTML!

**Comment by danilw** [comment]
im also on Linux, did not test on WIndows

I can not make PR [as I know](https://danilw.github.io/GLSL-howto/1.png), and this change too small for this much effort...

**Comment by lawnjelly** [comment]
Blimey I didn't know github did that. Sure I'll fix it. :+1: Thanks!
